# Implementação do Multi-Layer Perceptron em R

In [1]:
# Iniciar o Colab com R
# https://colab.research.google.com/#create=true&language=r

Usando a função logistica como função de ativação

Razões:

1. Introduz não-linearidade
2. Produz saída entre 0 e 1 (probabilidade)
3. Tem derivada simples, facilitando o backpropagation

In [2]:
#a função de ativação 
funcao.ativacao <- function(v){
    #funcao logistica
    y <- 1/(1+exp(-v))

    return(y)
}

In [3]:
#implementando a derivada da função logistica
der.funcao.ativacao <- function(y){
    derivada <- y * (1-y)

    return(derivada)
}

In [4]:
#criando uma arquitetura para a MLP
arquitetura <- function(num.entrada, num.escondida, num.saida,
                        funcao.ativacao, der.funcao.ativacao) {
    arq <- list()

    #parametro da rede
    arq$num.entrada <- num.entrada
    arq$num.escondida <- num.escondida
    arq$num.saida <- num.saida
    arq$funcao.ativacao <- funcao.ativacao
    arq$der.funcao.ativacao <- der.funcao.ativacao

    # 2 neuronios na camada escondida
    #
    #       Ent1    Ent2   Bias
    # 1     w11     w12    w13
    # 2     w21     w22    w23

    # Pesos conectando entrada e escondida
    #adicionamos +1 por conta dos pesos do bias
    num.pesos.entrada.escondida <- (num.entrada+1)*num.escondida
    arq$escondida <- matrix(runif(min=-0.5, max=0.5, num.pesos.entrada.escondida),
                                nrow = num.escondida, ncol=num.entrada+1)

    #Pesos conectando escondida e saida
    num.pesos.escondida.saida <- (num.escondida+1)*num.saida
    arq$saida <- matrix(runif(min=-0.5,max=0.5, num.pesos.escondida.saida),
                            nrow = num.saida, ncol = num.escondida+1)

    return(arq)

}

fase de propagação

In [5]:
mlp.propagacao <- function(arq, dados.exemplos){

    #entrada -> camada escondida
    #multiplicacao de matriz : %*%
    v.entrada.escondida <- arq$escondida %*% as.numeric(c(dados.exemplos, 1))
    y.entrada.escondida <- arq$funcao.ativacao(v.entrada.escondida)

    #camada escondida -> camada de saida
    v.escondida.saida <- arq$saida %*% c(y.entrada.escondida, 1)
    y.escondida.saida <- arq$funcao.ativacao(v.escondida.saida)

    #resultados
    resultados <- list()
    resultados$v.entrada.escondida <- v.entrada.escondida
    resultados$y.entrada.escondida <- y.entrada.escondida
    resultados$v.escondida.saida <- v.escondida.saida
    resultados$y.escondida.saida <- y.escondida.saida

    return(resultados)
}

**Backpropagation**

 O que é: Um método supervisionado de aprendizado que utiliza o gradiente descendente para otimizar pesos e vieses (bias).

Objetivo: Minimizar a função de custo (erro) entre a saída prevista e a saída real.

Importância: Sem o backpropagation, redes neurais multicamadas não conseguiriam ajustar eficientemente as camadas ocultas

Funcionamento:

**Forward Pass (Propagação Direta)**: Dados de entrada passam pela rede, camadas ocultas processam e geram uma saída.

**Cálculo do Erro:** A saída da rede é comparada com a "verdade básica" (saída desejada), gerando uma função de perda.

**Backward Pass (Retropropagação):** O erro é propagado de volta. O algoritmo calcula a derivada parcial da função de custo em relação a cada peso, utilizando a regra da cadeia do cálculo.

**Atualização dos Pesos:** Os pesos são ajustados (subtraindo o gradiente multiplicado por uma taxa de aprendizado) para reduzir o erro na próxima iteração.

In [6]:
mlp.retropropagacao <- function(arq, dados, n, limiar){

    erroQuadratico <- 2 * limiar
    epocas <- 0

    #O treinamento ocorre enquanto o erroQuad > limiar
    while(erroQuadratico > limiar){
        erroQuadratico <- 0

        #Treino para todos os exemplos(i.e epoca)
        for(i in 1:nrow(dados)){
            #pega um exemplo de entrada
            x.entrada <- dados[i,1:arq$num.entrada]
            x.saida <- dados[i, ncol(dados)]

            #Foward Pass
            #pega a saida da rede para o exemplo
            result <- mlp.propagacao(arq, x.entrada)
            y <- result$y.escondida.saida

            #Calculo do erro
            erro <- x.saida - y

            #soma erro quadratico
            erroQuadratico <- erroQuadratico + erro*erro

            #Backward Pass

            # Gradiente local no neuronio de saida
            # erro * derivada da funcao de ativacao
            gradiente.local.saida <- erro * arq$der.funcao.ativacao(y)

            # Gradiente local no neuronio escondido
            # derivada da funcao de ativacao no neuronio escondido * soma dos gradientes
            # locais dos neuronios conectados na proxima camada * pesos conectando a camada
            # escondida com a saida
            pesos.saida <- arq$saida[,1:arq$num.escondida]
            gradiente.local.escondida <- as.numeric(arq$der.funcao.ativacao(result$y.entrada.escondida)) * (gradiente.local.saida %*% pesos.saida)

            #Atualizando os pesos sinapticos
            arq$saida <- arq$saida + n * (gradiente.local.saida %*% c(result$y.entrada.escondida, 1))

            #escondida
            arq$escondida <- arq$escondida + n * (t(gradiente.local.escondida) %*% as.numeric(c(x.entrada,1)))
        }

        erroQuadratico <- erroQuadratico / nrow(dados)
        cat("Erro Quadratico Medio = ", erroQuadratico, "\n")
        flush.console()
        epocas <- epocas+1
    }

    retorno <- list()
    retorno$arq <- arq
    retorno$epocas <- epocas

    return(retorno)
}

In [7]:
# Leitura de uma tabela com os dados do problema XOR
dados <- read.table('XOR.txt')
print(dados)

  V1 V2 V3
1  0  0  0
2  0  1  1
3  1  0  1
4  1  1  0

In [8]:
# Nossa arquitetura
arq <- arquitetura(2,2,1,funcao.ativacao, der.funcao.ativacao)
print(arq)

$num.entrada
[1] 2

$num.escondida
[1] 2

$num.saida
[1] 1

$funcao.ativacao
<srcref: file "" chars 2:20 to 7:1>

$der.funcao.ativacao
<srcref: file "" chars 2:24 to 6:1>

$escondida
          [,1]        [,2]       [,3]
[1,] 0.3778651 -0.24078653 -0.3652943
[2,] 0.3223562  0.02926528  0.2216363

$saida
          [,1]       [,2]      [,3]
[1,] 0.4726642 -0.4894914 0.2526804

In [9]:
# Vamos treinar nossa MLP
#taxa de aprendizado: 0.1
#limiar: 0.001
modelo <- mlp.retropropagacao(arq,dados,0.1,1e-3)
print(modelo)

Erro Quadratico Medio =  0.2539981
Erro Quadratico Medio =  0.2538812
Erro Quadratico Medio =  0.253773
Erro Quadratico Medio =  0.2536729
Erro Quadratico Medio =  0.2535801
Erro Quadratico Medio =  0.2534944
Erro Quadratico Medio =  0.253415

Erro Quadratico Medio =  0.2533415
Erro Quadratico Medio =  0.2532735
Erro Quadratico Medio =  0.2532106
Erro Quadratico Medio =  0.2531525
Erro Quadratico Medio =  0.2530987
Erro Quadratico Medio =  0.2530489
Erro Quadratico Medio =  0.2530028
Erro Quadratico Medio =  0.2529603
Erro Quadratico Medio =  0.2529209
Erro Quadratico Medio =  0.2528845
Erro Quadratico Medio =  0.2528508
Erro Quadratico Medio =  0.2528196
Erro Quadratico Medio =  0.2527908
Erro Quadratico Medio =  0.2527642
Erro Quadratico Medio =  0.2527395
Erro Quadratico Medio =  0.2527167
Erro Quadratico Medio =  0.2526956
Erro Quadratico Medio =  0.2526761
Erro Quadratico Medio =  0.2526581
Erro Quadratico Medio =  0.2526414
Erro Quadratico Medio =  0.252626
Erro Quadratico Medio =  0.2526117
Erro Quadratico Medio =  0.2525985
Erro Quadratico Medio =  0.2525863
Erro Quadratico Medio =  0.252575
Erro Quadratico Medio =  0.2525645
Erro Quadratico Medio =  0.2525548
Erro Quadratico Medio =  0.2525458
Erro Quadratico Medio =  0.2525375
Erro Quadratico Medio =  0.2525298
Erro Quadratico Medio =  0.2525227
Erro Quadratico Medio =  0.2525161
Erro Quadratico Medio =  0.25251
Erro Quadratico Medio =  0.2525043
Erro Quadratico Medio =  0.2524991
Erro Quadratico Medio =  0.2524942
Erro Quadratico Medio =  0.2524897
Erro Quadratico Medio =  0.2524855
Erro Quadratico Medio =  0.2524816
Erro Quadratico Medio =  0.252478
Erro Quadratico Medio =  0.2524746
Erro Quadratico Medio =  0.2524715
Erro Quadratico Medio =  0.2524686
Erro Quadratico Medio =  0.2524659
Erro Quadratico Medio =  0.2524633
Erro Quadratico Medio =  0.252461
Erro Quadratico Medio =  0.2524588
Erro Quadratico Medio =  0.2524567
Erro Quadratico Medio =  0.2524548
Erro Quadratico Medio =  0.2524531
Erro Quadratico Medio =  0.2524514
Erro Quadratico Medio =  0.2524498
Erro Quadratico Medio =  0.2524484
Erro Quadratico Medio =  0.252447
Erro Quadratico Medio =  0.2524457
Erro Quadratico Medio =  0.2524445
Erro Quadratico Medio =  0.2524433
Erro Quadratico Medio =  0.2524423
Erro Quadratico Medio =  0.2524413
Erro Quadratico Medio =  0.2524403
Erro Quadratico Medio =  0.2524394
Erro Quadratico Medio =  0.2524385
Erro Quadratico Medio =  0.2524377
Erro Quadratico Medio =  0.2524369
Erro Quadratico Medio =  0.2524362
Erro Quadratico Medio =  0.2524355
Erro Quadratico Medio =  0.2524348
Erro Quadratico Medio =  0.2524342
Erro Quadratico Medio =  0.2524336
Erro Quadratico Medio =  0.252433
Erro Quadratico Medio =  0.2524324
Erro Quadratico Medio =  0.2524319
Erro Quadratico Medio =  0.2524313
Erro Quadratico Medio =  0.2524308
Erro Quadratico Medio =  0.2524303
Erro Quadratico Medio =  0.2524299
Erro Quadratico Medio =  0.2524294
Erro Quadratico Medio =  0.252429
Erro Quadratico Medio =  0.2524285
Erro Quadratico Medio =  0.2524281
Erro Quadratico Medio =  0.2524277
Erro Quadratico Medio =  0.2524273
Erro Quadratico Medio =  0.2524269
Erro Quadratico Medio =  0.2524265
Erro Quadratico Medio =  0.2524261
Erro Quadratico Medio =  0.2524257
Erro Quadratico Medio =  0.2524253
Erro Quadratico Medio =  0.252425
Erro Quadratico Medio =  0.2524246
Erro Quadratico Medio =  0.2524243
Erro Quadratico Medio =  0.2524239
Erro Quadratico Medio =  0.2524236
Erro Quadratico Medio =  0.2524232
Erro Quadratico Medio =  0.2524229
Erro Quadratico Medio =  0.2524225
Erro Quadratico Medio =  0.2524222
Erro Quadratico Medio =  0.2524219
Erro Quadratico Medio =  0.2524215
Erro Quadratico Medio =  0.2524212
Erro Quadratico Medio =  0.2524209
Erro Quadratico Medio =  0.2524206
Erro Quadratico Medio =  0.2524202
Erro Quadratico Medio =  0.2524199
Erro Quadratico Medio =  0.2524196
Erro Quadratico Medio =  0.2524193
Erro Quadratico Medio =  0.252419
Erro Quadratico Medio =  0.2524187
Erro Quadratico Medio =  0.2524183
Erro Quadratico Medio =  0.252418
Erro Quadratico Medio =  0.2524177
Erro Quadratico Medio =  0.2524174
Erro Quadratico Medio =  0.2524171
Erro Quadratico Medio =  0.2524168
Erro Quadratico Medio =  0.2524165
Erro Quadratico Medio =  0.2524162
Erro Quadratico Medio =  0.2524159
Erro Quadratico Medio =  0.2524155
Erro Quadratico Medio =  0.2524152
Erro Quadratico Medio =  0.2524149
Erro Quadratico Medio =  0.2524146
Erro Quadratico Medio =  0.2524143
Erro Quadratico Medio =  0.252414
Erro Quadratico Medio =  0.2524137
Erro Quadratico Medio =  0.2524134
Erro Quadratico Medio =  0.2524131
Erro Quadratico Medio =  0.2524128
Erro Quadratico Medio =  0.2524125
Erro Quadratico Medio =  0.2524122
Erro Quadratico Medio =  0.2524119
Erro Quadratico Medio =  0.2524116
Erro Quadratico Medio =  0.2524113
Erro Quadratico Medio =  0.252411
Erro Quadratico Medio =  0.2524107
Erro Quadratico Medio =  0.2524104
Erro Quadratico Medio =  0.25241
Erro Quadratico Medio =  0.2524097
Erro Quadratico Medio =  0.2524094
Erro Quadratico Medio =  0.2524091
Erro Quadratico Medio =  0.2524088
Erro Quadratico Medio =  0.2524085
Erro Quadratico Medio =  0.2524082
Erro Quadratico Medio =  0.2524079
Erro Quadratico Medio =  0.2524076
Erro Quadratico Medio =  0.2524073
Erro Quadratico Medio =  0.252407
Erro Quadratico Medio =  0.2524067
Erro Quadratico Medio =  0.2524064
Erro Quadratico Medio =  0.2524061
Erro Quadratico Medio =  0.2524058
Erro Quadratico Medio =  0.2524055
Erro Quadratico Medio =  0.2524052
Erro Quadratico Medio =  0.2524049
Erro Quadratico Medio =  0.2524046
Erro Quadratico Medio =  0.2524043
Erro Quadratico Medio =  0.252404
Erro Quadratico Medio =  0.2524037
Erro Quadratico Medio =  0.2524034
Erro Quadratico Medio =  0.2524031
Erro Quadratico Medio =  0.2524028
Erro Quadratico Medio =  0.2524025
Erro Quadratico Medio =  0.2524022
Erro Quadratico Medio =  0.2524019
Erro Quadratico Medio =  0.2524016
Erro Quadratico Medio =  0.2524013
Erro Quadratico Medio =  0.252401
Erro Quadratico Medio =  0.2524007
Erro Quadratico Medio =  0.2524004
Erro Quadratico Medio =  0.2524001
Erro Quadratico Medio =  0.2523998
Erro Quadratico Medio =  0.2523995
Erro Quadratico Medio =  0.2523992
Erro Quadratico Medio =  0.2523988
Erro Quadratico Medio =  0.2523985
Erro Quadratico Medio =  0.2523982
Erro Quadratico Medio =  0.2523979
Erro Quadratico Medio =  0.2523976
Erro Quadratico Medio =  0.2523973
Erro Quadratico Medio =  0.252397
Erro Quadratico Medio =  0.2523967
Erro Quadratico Medio =  0.2523964
Erro Quadratico Medio =  0.2523961
Erro Quadratico Medio =  0.2523958
Erro Quadratico Medio =  0.2523955
Erro Quadratico Medio =  0.2523952
Erro Quadratico Medio =  0.2523949
Erro Quadratico Medio =  0.2523946
Erro Quadratico Medio =  0.2523943
Erro Quadratico Medio =  0.252394
Erro Quadratico Medio =  0.2523937
Erro Quadratico Medio =  0.2523934
Erro Quadratico Medio =  0.2523931
Erro Quadratico Medio =  0.2523928
Erro Quadratico Medio =  0.2523925
Erro Quadratico Medio =  0.2523922
Erro Quadratico Medio =  0.2523919
Erro Quadratico Medio =  0.2523916
Erro Quadratico Medio =  0.2523913
Erro Quadratico Medio =  0.252391
Erro Quadratico Medio =  0.2523907
Erro Quadratico Medio =  0.2523904
Erro Quadratico Medio =  0.2523901
Erro Quadratico Medio =  0.2523898
Erro Quadratico Medio =  0.2523895
Erro Quadratico Medio =  0.2523892
Erro Quadratico Medio =  0.2523889
Erro Quadratico Medio =  0.2523886
Erro Quadratico Medio =  0.2523883
Erro Quadratico Medio =  0.252388
Erro Quadratico Medio =  0.2523877
Erro Quadratico Medio =  0.2523874
Erro Quadratico Medio =  0.2523871
Erro Quadratico Medio =  0.2523868
Erro Quadratico Medio =  0.2523865
Erro Quadratico Medio =  0.2523862
Erro Quadratico Medio =  0.2523859
Erro Quadratico Medio =  0.2523856
Erro Quadratico Medio =  0.2523853
Erro Quadratico Medio =  0.252385
Erro Quadratico Medio =  0.2523847
Erro Quadratico Medio =  0.2523844
Erro Quadratico Medio =  0.2523841
Erro Quadratico Medio =  0.2523838
Erro Quadratico Medio =  0.2523835
Erro Quadratico Medio =  0.2523832
Erro Quadratico Medio =  0.2523829
Erro Quadratico Medio =  0.2523826
Erro Quadratico Medio =  0.2523823
Erro Quadratico Medio =  0.252382
Erro Quadratico Medio =  0.2523817
Erro Quadratico Medio =  0.2523814
Erro Quadratico Medio =  0.2523811
Erro Quadratico Medio =  0.2523808
Erro Quadratico Medio =  0.2523805
Erro Quadratico Medio =  0.2523802
Erro Quadratico Medio =  0.2523799
Erro Quadratico Medio =  0.2523797
Erro Quadratico Medio =  0.2523794
Erro Quadratico Medio =  0.2523791
Erro Quadratico Medio =  0.2523788
Erro Quadratico Medio =  0.2523785
Erro Quadratico Medio =  0.2523782
Erro Quadratico Medio =  0.2523779
Erro Quadratico Medio =  0.2523776
Erro Quadratico Medio =  0.2523773
Erro Quadratico Medio =  0.252377
Erro Quadratico Medio =  0.2523767
Erro Quadratico Medio =  0.2523764
Erro Quadratico Medio =  0.2523761
Erro Quadratico Medio =  0.2523758
Erro Quadratico Medio =  0.2523755
Erro Quadratico Medio =  0.2523752
Erro Quadratico Medio =  0.2523749
Erro Quadratico Medio =  0.2523746
Erro Quadratico Medio =  0.2523743
Erro Quadratico Medio =  0.252374
Erro Quadratico Medio =  0.2523737
Erro Quadratico Medio =  0.2523734
Erro Quadratico Medio =  0.2523731
Erro Quadratico Medio =  0.2523728
Erro Quadratico Medio =  0.2523725
Erro Quadratico Medio =  0.2523722
Erro Quadratico Medio =  0.2523719
Erro Quadratico Medio =  0.2523716
Erro Quadratico Medio =  0.2523713
Erro Quadratico Medio =  0.252371
Erro Quadratico Medio =  0.2523707
Erro Quadratico Medio =  0.2523704
Erro Quadratico Medio =  0.2523701
Erro Quadratico Medio =  0.2523698
Erro Quadratico Medio =  0.2523695
Erro Quadratico Medio =  0.2523692
Erro Quadratico Medio =  0.2523689
Erro Quadratico Medio =  0.2523687
Erro Quadratico Medio =  0.2523684
Erro Quadratico Medio =  0.2523681
Erro Quadratico Medio =  0.2523678
Erro Quadratico Medio =  0.2523675
Erro Quadratico Medio =  0.2523672
Erro Quadratico Medio =  0.2523669
Erro Quadratico Medio =  0.2523666
Erro Quadratico Medio =  0.2523663
Erro Quadratico Medio =  0.252366
Erro Quadratico Medio =  0.2523657
Erro Quadratico Medio =  0.2523654
Erro Quadratico Medio =  0.2523651
Erro Quadratico Medio =  0.2523648
Erro Quadratico Medio =  0.2523645
Erro Quadratico Medio =  0.2523642
Erro Quadratico Medio =  0.2523639
Erro Quadratico Medio =  0.2523636
Erro Quadratico Medio =  0.2523633
Erro Quadratico Medio =  0.252363
Erro Quadratico Medio =  0.2523627
Erro Quadratico Medio =  0.2523624
Erro Quadratico Medio =  0.2523621
Erro Quadratico Medio =  0.2523618
Erro Quadratico Medio =  0.2523615
Erro Quadratico Medio =  0.2523613
Erro Quadratico Medio =  0.252361
Erro Quadratico Medio =  0.2523607
Erro Quadratico Medio =  0.2523604
Erro Quadratico Medio =  0.2523601
Erro Quadratico Medio =  0.2523598
Erro Quadratico Medio =  0.2523595
Erro Quadratico Medio =  0.2523592
Erro Quadratico Medio =  0.2523589
Erro Quadratico Medio =  0.2523586
Erro Quadratico Medio =  0.2523583
Erro Quadratico Medio =  0.252358
Erro Quadratico Medio =  0.2523577
Erro Quadratico Medio =  0.2523574
Erro Quadratico Medio =  0.2523571
Erro Quadratico Medio =  0.2523568
Erro Quadratico Medio =  0.2523565
Erro Quadratico Medio =  0.2523562
Erro Quadratico Medio =  0.2523559
Erro Quadratico Medio =  0.2523556
Erro Quadratico Medio =  0.2523553
Erro Quadratico Medio =  0.2523551
Erro Quadratico Medio =  0.2523548
Erro Quadratico Medio =  0.2523545
Erro Quadratico Medio =  0.2523542
Erro Quadratico Medio =  0.2523539
Erro Quadratico Medio =  0.2523536
Erro Quadratico Medio =  0.2523533
Erro Quadratico Medio =  0.252353
Erro Quadratico Medio =  0.2523527
Erro Quadratico Medio =  0.2523524
Erro Quadratico Medio =  0.2523521
Erro Quadratico Medio =  0.2523518
Erro Quadratico Medio =  0.2523515
Erro Quadratico Medio =  0.2523512
Erro Quadratico Medio =  0.2523509
Erro Quadratico Medio =  0.2523506
Erro Quadratico Medio =  0.2523503
Erro Quadratico Medio =  0.25235
Erro Quadratico Medio =  0.2523497
Erro Quadratico Medio =  0.2523495
Erro Quadratico Medio =  0.2523492
Erro Quadratico Medio =  0.2523489
Erro Quadratico Medio =  0.2523486
Erro Quadratico Medio =  0.2523483
Erro Quadratico Medio =  0.252348
Erro Quadratico Medio =  0.2523477
Erro Quadratico Medio =  0.2523474
Erro Quadratico Medio =  0.2523471
Erro Quadratico Medio =  0.2523468
Erro Quadratico Medio =  0.2523465
Erro Quadratico Medio =  0.2523462
Erro Quadratico Medio =  0.2523459
Erro Quadratico Medio =  0.2523456
Erro Quadratico Medio =  0.2523453
Erro Quadratico Medio =  0.252345
Erro Quadratico Medio =  0.2523447
Erro Quadratico Medio =  0.2523444
Erro Quadratico Medio =  0.2523442
Erro Quadratico Medio =  0.2523439
Erro Quadratico Medio =  0.2523436
Erro Quadratico Medio =  0.2523433
Erro Quadratico Medio =  0.252343
Erro Quadratico Medio =  0.2523427
Erro Quadratico Medio =  0.2523424
Erro Quadratico Medio =  0.2523421
Erro Quadratico Medio =  0.2523418
Erro Quadratico Medio =  0.2523415
Erro Quadratico Medio =  0.2523412
Erro Quadratico Medio =  0.2523409
Erro Quadratico Medio =  0.2523406
Erro Quadratico Medio =  0.2523403
Erro Quadratico Medio =  0.25234
Erro Quadratico Medio =  0.2523397
Erro Quadratico Medio =  0.2523394
Erro Quadratico Medio =  0.2523392
Erro Quadratico Medio =  0.2523389
Erro Quadratico Medio =  0.2523386
Erro Quadratico Medio =  0.2523383
Erro Quadratico Medio =  0.252338
Erro Quadratico Medio =  0.2523377
Erro Quadratico Medio =  0.2523374
Erro Quadratico Medio =  0.2523371
Erro Quadratico Medio =  0.2523368
Erro Quadratico Medio =  0.2523365
Erro Quadratico Medio =  0.2523362
Erro Quadratico Medio =  0.2523359
Erro Quadratico Medio =  0.2523356
Erro Quadratico Medio =  0.2523353
Erro Quadratico Medio =  0.252335
Erro Quadratico Medio =  0.2523347
Erro Quadratico Medio =  0.2523344
Erro Quadratico Medio =  0.2523342
Erro Quadratico Medio =  0.2523339
Erro Quadratico Medio =  0.2523336
Erro Quadratico Medio =  0.2523333
Erro Quadratico Medio =  0.252333
Erro Quadratico Medio =  0.2523327
Erro Quadratico Medio =  0.2523324
Erro Quadratico Medio =  0.2523321
Erro Quadratico Medio =  0.2523318
Erro Quadratico Medio =  0.2523315
Erro Quadratico Medio =  0.2523312
Erro Quadratico Medio =  0.2523309
Erro Quadratico Medio =  0.2523306
Erro Quadratico Medio =  0.2523303
Erro Quadratico Medio =  0.25233
Erro Quadratico Medio =  0.2523297
Erro Quadratico Medio =  0.2523295
Erro Quadratico Medio =  0.2523292
Erro Quadratico Medio =  0.2523289
Erro Quadratico Medio =  0.2523286
Erro Quadratico Medio =  0.2523283
Erro Quadratico Medio =  0.252328
Erro Quadratico Medio =  0.2523277
Erro Quadratico Medio =  0.2523274
Erro Quadratico Medio =  0.2523271
Erro Quadratico Medio =  0.2523268
Erro Quadratico Medio =  0.2523265
Erro Quadratico Medio =  0.2523262
Erro Quadratico Medio =  0.2523259
Erro Quadratico Medio =  0.2523256
Erro Quadratico Medio =  0.2523253
Erro Quadratico Medio =  0.252325
Erro Quadratico Medio =  0.2523247
Erro Quadratico Medio =  0.2523245
Erro Quadratico Medio =  0.2523242
Erro Quadratico Medio =  0.2523239
Erro Quadratico Medio =  0.2523236
Erro Quadratico Medio =  0.2523233
Erro Quadratico Medio =  0.252323
Erro Quadratico Medio =  0.2523227
Erro Quadratico Medio =  0.2523224
Erro Quadratico Medio =  0.2523221
Erro Quadratico Medio =  0.2523218
Erro Quadratico Medio =  0.2523215
Erro Quadratico Medio =  0.2523212
Erro Quadratico Medio =  0.2523209
Erro Quadratico Medio =  0.2523206
Erro Quadratico Medio =  0.2523203
Erro Quadratico Medio =  0.25232
Erro Quadratico Medio =  0.2523197
Erro Quadratico Medio =  0.2523195
Erro Quadratico Medio =  0.2523192
Erro Quadratico Medio =  0.2523189
Erro Quadratico Medio =  0.2523186
Erro Quadratico Medio =  0.2523183
Erro Quadratico Medio =  0.252318
Erro Quadratico Medio =  0.2523177
Erro Quadratico Medio =  0.2523174
Erro Quadratico Medio =  0.2523171
Erro Quadratico Medio =  0.2523168
Erro Quadratico Medio =  0.2523165
Erro Quadratico Medio =  0.2523162
Erro Quadratico Medio =  0.2523159
Erro Quadratico Medio =  0.2523156
Erro Quadratico Medio =  0.2523153
Erro Quadratico Medio =  0.252315
Erro Quadratico Medio =  0.2523147
Erro Quadratico Medio =  0.2523144
Erro Quadratico Medio =  0.2523142
Erro Quadratico Medio =  0.2523139
Erro Quadratico Medio =  0.2523136
Erro Quadratico Medio =  0.2523133
Erro Quadratico Medio =  0.252313
Erro Quadratico Medio =  0.2523127
Erro Quadratico Medio =  0.2523124
Erro Quadratico Medio =  0.2523121
Erro Quadratico Medio =  0.2523118
Erro Quadratico Medio =  0.2523115
Erro Quadratico Medio =  0.2523112
Erro Quadratico Medio =  0.2523109
Erro Quadratico Medio =  0.2523106
Erro Quadratico Medio =  0.2523103
Erro Quadratico Medio =  0.25231
Erro Quadratico Medio =  0.2523097
Erro Quadratico Medio =  0.2523094
Erro Quadratico Medio =  0.2523091
Erro Quadratico Medio =  0.2523088
Erro Quadratico Medio =  0.2523086
Erro Quadratico Medio =  0.2523083
Erro Quadratico Medio =  0.252308
Erro Quadratico Medio =  0.2523077
Erro Quadratico Medio =  0.2523074
Erro Quadratico Medio =  0.2523071
Erro Quadratico Medio =  0.2523068
Erro Quadratico Medio =  0.2523065
Erro Quadratico Medio =  0.2523062
Erro Quadratico Medio =  0.2523059
Erro Quadratico Medio =  0.2523056
Erro Quadratico Medio =  0.2523053
Erro Quadratico Medio =  0.252305
Erro Quadratico Medio =  0.2523047
Erro Quadratico Medio =  0.2523044
Erro Quadratico Medio =  0.2523041
Erro Quadratico Medio =  0.2523038
Erro Quadratico Medio =  0.2523035
Erro Quadratico Medio =  0.2523032
Erro Quadratico Medio =  0.2523029
Erro Quadratico Medio =  0.2523026
Erro Quadratico Medio =  0.2523024
Erro Quadratico Medio =  0.2523021
Erro Quadratico Medio =  0.2523018
Erro Quadratico Medio =  0.2523015
Erro Quadratico Medio =  0.2523012
Erro Quadratico Medio =  0.2523009
Erro Quadratico Medio =  0.2523006
Erro Quadratico Medio =  0.2523003
Erro Quadratico Medio =  0.2523
Erro Quadratico Medio =  0.2522997
Erro Quadratico Medio =  0.2522994
Erro Quadratico Medio =  0.2522991
Erro Quadratico Medio =  0.2522988
Erro Quadratico Medio =  0.2522985
Erro Quadratico Medio =  0.2522982
Erro Quadratico Medio =  0.2522979
Erro Quadratico Medio =  0.2522976
Erro Quadratico Medio =  0.2522973
Erro Quadratico Medio =  0.252297
Erro Quadratico Medio =  0.2522967
Erro Quadratico Medio =  0.2522964
Erro Quadratico Medio =  0.2522961
Erro Quadratico Medio =  0.2522958
Erro Quadratico Medio =  0.2522955
Erro Quadratico Medio =  0.2522952
Erro Quadratico Medio =  0.252295
Erro Quadratico Medio =  0.2522947
Erro Quadratico Medio =  0.2522944
Erro Quadratico Medio =  0.2522941
Erro Quadratico Medio =  0.2522938
Erro Quadratico Medio =  0.2522935
Erro Quadratico Medio =  0.2522932
Erro Quadratico Medio =  0.2522929
Erro Quadratico Medio =  0.2522926
Erro Quadratico Medio =  0.2522923
Erro Quadratico Medio =  0.252292
Erro Quadratico Medio =  0.2522917
Erro Quadratico Medio =  0.2522914
Erro Quadratico Medio =  0.2522911
Erro Quadratico Medio =  0.2522908
Erro Quadratico Medio =  0.2522905
Erro Quadratico Medio =  0.2522902
Erro Quadratico Medio =  0.2522899
Erro Quadratico Medio =  0.2522896
Erro Quadratico Medio =  0.2522893
Erro Quadratico Medio =  0.252289
Erro Quadratico Medio =  0.2522887
Erro Quadratico Medio =  0.2522884
Erro Quadratico Medio =  0.2522881
Erro Quadratico Medio =  0.2522878
Erro Quadratico Medio =  0.2522875
Erro Quadratico Medio =  0.2522872
Erro Quadratico Medio =  0.2522869
Erro Quadratico Medio =  0.2522866
Erro Quadratico Medio =  0.2522863
Erro Quadratico Medio =  0.252286
Erro Quadratico Medio =  0.2522857
Erro Quadratico Medio =  0.2522854
Erro Quadratico Medio =  0.2522851
Erro Quadratico Medio =  0.2522848
Erro Quadratico Medio =  0.2522845
Erro Quadratico Medio =  0.2522842
Erro Quadratico Medio =  0.2522839
Erro Quadratico Medio =  0.2522836
Erro Quadratico Medio =  0.2522833
Erro Quadratico Medio =  0.2522831
Erro Quadratico Medio =  0.2522828
Erro Quadratico Medio =  0.2522825
Erro Quadratico Medio =  0.2522822
Erro Quadratico Medio =  0.2522819
Erro Quadratico Medio =  0.2522816
Erro Quadratico Medio =  0.2522813
Erro Quadratico Medio =  0.252281
Erro Quadratico Medio =  0.2522807
Erro Quadratico Medio =  0.2522804
Erro Quadratico Medio =  0.2522801

In [10]:
#Testando em dados novos
retorno <- mlp.propagacao(modelo$arq,c(0,1))
print(retorno$y.escondida.saida)

print(mlp.propagacao(modelo$arq,c(1,0))$y.escondida.saida)

print(mlp.propagacao(modelo$arq,c(1,1))$y.escondida.saida)

print(mlp.propagacao(modelo$arq,c(0,0))$y.escondida.saida)

          [,1]
[1,] 0.9637583
          [,1]
[1,] 0.9703739
           [,1]
[1,] 0.02814399
          [,1]
[1,] 0.0318687

In [11]:
# Leitura de dados sobre risco de crédito.
# Queremos prever, com base nas variáveis de entrada, se ocorrerá ou não um calote em 10 anos

dataset <- read.csv("creditset.csv")
dim(dataset)
head(dataset)

# clientid: identificação do cliente
# income: renda anual
# age: idade
# loan: empréstimo com data de no mínimo 10 anos atrás
# LTI: razão entre valor do empréstimo e renda anual
# default10yr: se ocorrerá (1) ou não (0) um calote em 10 anos

[1] 2000    6

  clientid income   age      loan      LTI          default10yr
1 1        66155.93 59.01702 8106.5321 0.1225367512 0
2 2        34415.15 48.11715 6564.7450 0.1907515807 0
3 3        57317.17 63.10805 8020.9533 0.1399397997 0
4 4        42709.53 45.75197 6103.6423 0.1429105321 0
5 5        66952.69 18.58434 8770.0992 0.1309895000 1
6 6        24904.06 57.47161   15.4986 0.0006223321 0

In [12]:
# Vamos utilizar como variáveis de entrada LTI e age
dados <- dataset[,c(3,5,6)]
dados[,1:2] <- scale(dados[,1:2]) # normalização dos dados (media 0 e desvio 1)
head(dados)

  age        LTI        default10yr
1  1.3639917  0.4188448 0
2  0.5421329  1.6027146 0
3  1.6724592  0.7208751 0
4  0.3637962  0.7724322 0
5 -1.6846667  0.5655424 1
6  1.2474667 -1.6969826 0

In [13]:
# Vamos escolher aleatoriamente dados para treino e teste.
# O conjunto de dados já está randomizado.
# Assim, Vamos pegar os primeiros 1400 exemplos para treino e o restante para teste
dados.treino <- dados[1:1400,]
dados.teste <- dados[1401:2000,]

In [14]:
# Vamos utilizar como variáveis de entrada LTI e age
dados <- dataset[,c(3,5,6)]
dados[,1:2] <- scale(dados[,1:2]) # normalização dos dados (media 0 e desvio 1)
head(dados)

  age        LTI        default10yr
1  1.3639917  0.4188448 0
2  0.5421329  1.6027146 0
3  1.6724592  0.7208751 0
4  0.3637962  0.7724322 0
5 -1.6846667  0.5655424 1
6  1.2474667 -1.6969826 0

In [15]:
# Vamos treinar nossa rede com 4 neurônios na camada escondida
modelo <- mlp.retropropagacao(arq,dados.treino,0.3,1e-3)
print(modelo)

Erro Quadratico Medio =  0.09022748
Erro Quadratico Medio =  0.04884193
Erro Quadratico Medio =  0.03851232
Erro Quadratico Medio =  0.03514291
Erro Quadratico Medio =  0.03365
Erro Quadratico Medio =  0.03285449
Erro Quadratico Medio =  0.03236515
Erro Quadratico Medio =  0.03200798
Erro Quadratico Medio =  0.03167479
Erro Quadratico Medio =  0.03126821
Erro Quadratico Medio =  0.03068287
Erro Quadratico Medio =  0.0298133
Erro Quadratico Medio =  0.02857201
Erro Quadratico Medio =  0.02690254
Erro Quadratico Medio =  0.02481879
Erro Quadratico Medio =  0.02247239
Erro Quadratico Medio =  0.02013302
Erro Quadratico Medio =  0.0180362
Erro Quadratico Medio =  0.01626979
Erro Quadratico Medio =  0.01481241
Erro Quadratico Medio =  0.01361361
Erro Quadratico Medio =  0.01262419
Erro Quadratico Medio =  0.01180064
Erro Quadratico Medio =  0.01110543
Erro Quadratico Medio =  0.01050775
Erro Quadratico Medio =  0.009984149
Erro Quadratico Medio =  0.009517924
Erro Quadratico Medio =  0.00909759
Erro Quadratico Medio =  0.008715328
Erro Quadratico Medio =  0.008365727
Erro Quadratico Medio =  0.008044901
Erro Quadratico Medio =  0.007749897
Erro Quadratico Medio =  0.007478327
Erro Quadratico Medio =  0.007228148
Erro Quadratico Medio =  0.006997541
Erro Quadratico Medio =  0.006784839
Erro Quadratico Medio =  0.006588504
Erro Quadratico Medio =  0.006407105
Erro Quadratico Medio =  0.006239314
Erro Quadratico Medio =  0.006083908
Erro Quadratico Medio =  0.005939758
Erro Quadratico Medio =  0.005805833
Erro Quadratico Medio =  0.005681191
Erro Quadratico Medio =  0.005564974
Erro Quadratico Medio =  0.005456407
Erro Quadratico Medio =  0.005354787
Erro Quadratico Medio =  0.005259479
Erro Quadratico Medio =  0.005169912
Erro Quadratico Medio =  0.005085571
Erro Quadratico Medio =  0.005005992
Erro Quadratico Medio =  0.004930758
Erro Quadratico Medio =  0.004859496
Erro Quadratico Medio =  0.004791868
Erro Quadratico Medio =  0.004727571
Erro Quadratico Medio =  0.004666333
Erro Quadratico Medio =  0.004607909
Erro Quadratico Medio =  0.004552079
Erro Quadratico Medio =  0.004498642
Erro Quadratico Medio =  0.00444742
Erro Quadratico Medio =  0.00439825
Erro Quadratico Medio =  0.004350986
Erro Quadratico Medio =  0.004305495
Erro Quadratico Medio =  0.004261656
Erro Quadratico Medio =  0.00421936
Erro Quadratico Medio =  0.004178507
Erro Quadratico Medio =  0.004139006
Erro Quadratico Medio =  0.004100776
Erro Quadratico Medio =  0.004063739
Erro Quadratico Medio =  0.004027826
Erro Quadratico Medio =  0.003992975
Erro Quadratico Medio =  0.003959127
Erro Quadratico Medio =  0.003926228
Erro Quadratico Medio =  0.003894228
Erro Quadratico Medio =  0.003863082
Erro Quadratico Medio =  0.003832747
Erro Quadratico Medio =  0.003803184
Erro Quadratico Medio =  0.003774357
Erro Quadratico Medio =  0.003746232
Erro Quadratico Medio =  0.003718778
Erro Quadratico Medio =  0.003691965
Erro Quadratico Medio =  0.003665766
Erro Quadratico Medio =  0.003640155
Erro Quadratico Medio =  0.003615108
Erro Quadratico Medio =  0.003590603
Erro Quadratico Medio =  0.003566619
Erro Quadratico Medio =  0.003543135
Erro Quadratico Medio =  0.003520133
Erro Quadratico Medio =  0.003497596
Erro Quadratico Medio =  0.003475507
Erro Quadratico Medio =  0.003453849
Erro Quadratico Medio =  0.003432609
Erro Quadratico Medio =  0.003411772
Erro Quadratico Medio =  0.003391324
Erro Quadratico Medio =  0.003371254
Erro Quadratico Medio =  0.003351549
Erro Quadratico Medio =  0.003332196
Erro Quadratico Medio =  0.003313187
Erro Quadratico Medio =  0.00329451
Erro Quadratico Medio =  0.003276154
Erro Quadratico Medio =  0.003258112
Erro Quadratico Medio =  0.003240373
Erro Quadratico Medio =  0.00322293
Erro Quadratico Medio =  0.003205773
Erro Quadratico Medio =  0.003188894
Erro Quadratico Medio =  0.003172287
Erro Quadratico Medio =  0.003155944
Erro Quadratico Medio =  0.003139858
Erro Quadratico Medio =  0.003124022
Erro Quadratico Medio =  0.003108429
Erro Quadratico Medio =  0.003093074
Erro Quadratico Medio =  0.003077951
Erro Quadratico Medio =  0.003063053
Erro Quadratico Medio =  0.003048375
Erro Quadratico Medio =  0.003033912
Erro Quadratico Medio =  0.003019659
Erro Quadratico Medio =  0.003005611
Erro Quadratico Medio =  0.002991762
Erro Quadratico Medio =  0.002978109
Erro Quadratico Medio =  0.002964646
Erro Quadratico Medio =  0.00295137
Erro Quadratico Medio =  0.002938276
Erro Quadratico Medio =  0.00292536
Erro Quadratico Medio =  0.002912618
Erro Quadratico Medio =  0.002900047
Erro Quadratico Medio =  0.002887643
Erro Quadratico Medio =  0.002875402
Erro Quadratico Medio =  0.00286332
Erro Quadratico Medio =  0.002851395
Erro Quadratico Medio =  0.002839624
Erro Quadratico Medio =  0.002828002
Erro Quadratico Medio =  0.002816527
Erro Quadratico Medio =  0.002805196
Erro Quadratico Medio =  0.002794006
Erro Quadratico Medio =  0.002782954
Erro Quadratico Medio =  0.002772038
Erro Quadratico Medio =  0.002761255
Erro Quadratico Medio =  0.002750602
Erro Quadratico Medio =  0.002740077
Erro Quadratico Medio =  0.002729677
Erro Quadratico Medio =  0.0027194
Erro Quadratico Medio =  0.002709244
Erro Quadratico Medio =  0.002699206
Erro Quadratico Medio =  0.002689284
Erro Quadratico Medio =  0.002679477
Erro Quadratico Medio =  0.002669781
Erro Quadratico Medio =  0.002660195
Erro Quadratico Medio =  0.002650718
Erro Quadratico Medio =  0.002641346
Erro Quadratico Medio =  0.002632078
Erro Quadratico Medio =  0.002622913
Erro Quadratico Medio =  0.002613849
Erro Quadratico Medio =  0.002604883
Erro Quadratico Medio =  0.002596014
Erro Quadratico Medio =  0.002587241
Erro Quadratico Medio =  0.002578561
Erro Quadratico Medio =  0.002569974
Erro Quadratico Medio =  0.002561477
Erro Quadratico Medio =  0.00255307
Erro Quadratico Medio =  0.00254475
Erro Quadratico Medio =  0.002536516
Erro Quadratico Medio =  0.002528367
Erro Quadratico Medio =  0.002520302
Erro Quadratico Medio =  0.002512319
Erro Quadratico Medio =  0.002504416
Erro Quadratico Medio =  0.002496593
Erro Quadratico Medio =  0.002488848
Erro Quadratico Medio =  0.00248118
Erro Quadratico Medio =  0.002473587
Erro Quadratico Medio =  0.00246607
Erro Quadratico Medio =  0.002458625
Erro Quadratico Medio =  0.002451253
Erro Quadratico Medio =  0.002443952
Erro Quadratico Medio =  0.002436722
Erro Quadratico Medio =  0.00242956
Erro Quadratico Medio =  0.002422466
Erro Quadratico Medio =  0.002415439
Erro Quadratico Medio =  0.002408478
Erro Quadratico Medio =  0.002401582
Erro Quadratico Medio =  0.00239475
Erro Quadratico Medio =  0.002387982
Erro Quadratico Medio =  0.002381275
Erro Quadratico Medio =  0.002374629
Erro Quadratico Medio =  0.002368044
Erro Quadratico Medio =  0.002361519
Erro Quadratico Medio =  0.002355052
Erro Quadratico Medio =  0.002348643
Erro Quadratico Medio =  0.002342291
Erro Quadratico Medio =  0.002335995
Erro Quadratico Medio =  0.002329755
Erro Quadratico Medio =  0.002323569
Erro Quadratico Medio =  0.002317437
Erro Quadratico Medio =  0.002311358
Erro Quadratico Medio =  0.002305332
Erro Quadratico Medio =  0.002299357
Erro Quadratico Medio =  0.002293434
Erro Quadratico Medio =  0.00228756
Erro Quadratico Medio =  0.002281737
Erro Quadratico Medio =  0.002275962
Erro Quadratico Medio =  0.002270236
Erro Quadratico Medio =  0.002264557
Erro Quadratico Medio =  0.002258926
Erro Quadratico Medio =  0.002253341
Erro Quadratico Medio =  0.002247802
Erro Quadratico Medio =  0.002242308
Erro Quadratico Medio =  0.002236859
Erro Quadratico Medio =  0.002231454
Erro Quadratico Medio =  0.002226092
Erro Quadratico Medio =  0.002220774
Erro Quadratico Medio =  0.002215498
Erro Quadratico Medio =  0.002210264
Erro Quadratico Medio =  0.002205071
Erro Quadratico Medio =  0.002199919
Erro Quadratico Medio =  0.002194808
Erro Quadratico Medio =  0.002189736
Erro Quadratico Medio =  0.002184704
Erro Quadratico Medio =  0.002179711
Erro Quadratico Medio =  0.002174757
Erro Quadratico Medio =  0.00216984
Erro Quadratico Medio =  0.002164961
Erro Quadratico Medio =  0.002160119
Erro Quadratico Medio =  0.002155313
Erro Quadratico Medio =  0.002150544
Erro Quadratico Medio =  0.002145811
Erro Quadratico Medio =  0.002141113
Erro Quadratico Medio =  0.00213645
Erro Quadratico Medio =  0.002131822
Erro Quadratico Medio =  0.002127227
Erro Quadratico Medio =  0.002122667
Erro Quadratico Medio =  0.00211814
Erro Quadratico Medio =  0.002113646
Erro Quadratico Medio =  0.002109185
Erro Quadratico Medio =  0.002104756
Erro Quadratico Medio =  0.002100358
Erro Quadratico Medio =  0.002095993
Erro Quadratico Medio =  0.002091658
Erro Quadratico Medio =  0.002087355
Erro Quadratico Medio =  0.002083082
Erro Quadratico Medio =  0.002078839
Erro Quadratico Medio =  0.002074626
Erro Quadratico Medio =  0.002070443
Erro Quadratico Medio =  0.002066289
Erro Quadratico Medio =  0.002062164
Erro Quadratico Medio =  0.002058067
Erro Quadratico Medio =  0.002053999
Erro Quadratico Medio =  0.002049959
Erro Quadratico Medio =  0.002045946
Erro Quadratico Medio =  0.002041961
Erro Quadratico Medio =  0.002038003
Erro Quadratico Medio =  0.002034072
Erro Quadratico Medio =  0.002030167
Erro Quadratico Medio =  0.002026289
Erro Quadratico Medio =  0.002022437
Erro Quadratico Medio =  0.002018611
Erro Quadratico Medio =  0.00201481
Erro Quadratico Medio =  0.002011034
Erro Quadratico Medio =  0.002007284
Erro Quadratico Medio =  0.002003558
Erro Quadratico Medio =  0.001999857
Erro Quadratico Medio =  0.00199618
Erro Quadratico Medio =  0.001992527
Erro Quadratico Medio =  0.001988898
Erro Quadratico Medio =  0.001985292
Erro Quadratico Medio =  0.00198171
Erro Quadratico Medio =  0.001978151
Erro Quadratico Medio =  0.001974615
Erro Quadratico Medio =  0.001971101
Erro Quadratico Medio =  0.00196761
Erro Quadratico Medio =  0.001964141
Erro Quadratico Medio =  0.001960694
Erro Quadratico Medio =  0.001957269
Erro Quadratico Medio =  0.001953866
Erro Quadratico Medio =  0.001950484
Erro Quadratico Medio =  0.001947123
Erro Quadratico Medio =  0.001943784
Erro Quadratico Medio =  0.001940465
Erro Quadratico Medio =  0.001937167
Erro Quadratico Medio =  0.001933889
Erro Quadratico Medio =  0.001930632
Erro Quadratico Medio =  0.001927394
Erro Quadratico Medio =  0.001924177
Erro Quadratico Medio =  0.001920979
Erro Quadratico Medio =  0.001917801
Erro Quadratico Medio =  0.001914642
Erro Quadratico Medio =  0.001911502
Erro Quadratico Medio =  0.001908382
Erro Quadratico Medio =  0.00190528
Erro Quadratico Medio =  0.001902197
Erro Quadratico Medio =  0.001899133
Erro Quadratico Medio =  0.001896087
Erro Quadratico Medio =  0.001893059
Erro Quadratico Medio =  0.001890049
Erro Quadratico Medio =  0.001887057
Erro Quadratico Medio =  0.001884083
Erro Quadratico Medio =  0.001881127
Erro Quadratico Medio =  0.001878188
Erro Quadratico Medio =  0.001875266
Erro Quadratico Medio =  0.001872361
Erro Quadratico Medio =  0.001869474
Erro Quadratico Medio =  0.001866603
Erro Quadratico Medio =  0.001863749
Erro Quadratico Medio =  0.001860912
Erro Quadratico Medio =  0.001858091
Erro Quadratico Medio =  0.001855286
Erro Quadratico Medio =  0.001852498
Erro Quadratico Medio =  0.001849725
Erro Quadratico Medio =  0.001846969
Erro Quadratico Medio =  0.001844228
Erro Quadratico Medio =  0.001841503
Erro Quadratico Medio =  0.001838794
Erro Quadratico Medio =  0.0018361
Erro Quadratico Medio =  0.001833421
Erro Quadratico Medio =  0.001830758
Erro Quadratico Medio =  0.001828109
Erro Quadratico Medio =  0.001825476
Erro Quadratico Medio =  0.001822857
Erro Quadratico Medio =  0.001820253
Erro Quadratico Medio =  0.001817664
Erro Quadratico Medio =  0.001815089
Erro Quadratico Medio =  0.001812528
Erro Quadratico Medio =  0.001809982
Erro Quadratico Medio =  0.001807449
Erro Quadratico Medio =  0.001804931
Erro Quadratico Medio =  0.001802427
Erro Quadratico Medio =  0.001799936
Erro Quadratico Medio =  0.00179746
Erro Quadratico Medio =  0.001794996
Erro Quadratico Medio =  0.001792547
Erro Quadratico Medio =  0.00179011
Erro Quadratico Medio =  0.001787687
Erro Quadratico Medio =  0.001785278
Erro Quadratico Medio =  0.001782881
Erro Quadratico Medio =  0.001780497
Erro Quadratico Medio =  0.001778126
Erro Quadratico Medio =  0.001775768
Erro Quadratico Medio =  0.001773423
Erro Quadratico Medio =  0.00177109
Erro Quadratico Medio =  0.00176877
Erro Quadratico Medio =  0.001766462
Erro Quadratico Medio =  0.001764167
Erro Quadratico Medio =  0.001761884
Erro Quadratico Medio =  0.001759613
Erro Quadratico Medio =  0.001757354
Erro Quadratico Medio =  0.001755107
Erro Quadratico Medio =  0.001752872
Erro Quadratico Medio =  0.001750649
Erro Quadratico Medio =  0.001748437
Erro Quadratico Medio =  0.001746237
Erro Quadratico Medio =  0.001744049
Erro Quadratico Medio =  0.001741872
Erro Quadratico Medio =  0.001739707
Erro Quadratico Medio =  0.001737552
Erro Quadratico Medio =  0.001735409
Erro Quadratico Medio =  0.001733278
Erro Quadratico Medio =  0.001731157
Erro Quadratico Medio =  0.001729047
Erro Quadratico Medio =  0.001726948
Erro Quadratico Medio =  0.00172486
Erro Quadratico Medio =  0.001722783
Erro Quadratico Medio =  0.001720716
Erro Quadratico Medio =  0.001718661
Erro Quadratico Medio =  0.001716615
Erro Quadratico Medio =  0.00171458
Erro Quadratico Medio =  0.001712556
Erro Quadratico Medio =  0.001710541
Erro Quadratico Medio =  0.001708537
Erro Quadratico Medio =  0.001706544
Erro Quadratico Medio =  0.00170456
Erro Quadratico Medio =  0.001702586
Erro Quadratico Medio =  0.001700623
Erro Quadratico Medio =  0.001698669
Erro Quadratico Medio =  0.001696725
Erro Quadratico Medio =  0.001694791
Erro Quadratico Medio =  0.001692866
Erro Quadratico Medio =  0.001690951
Erro Quadratico Medio =  0.001689046
Erro Quadratico Medio =  0.00168715
Erro Quadratico Medio =  0.001685264
Erro Quadratico Medio =  0.001683387
Erro Quadratico Medio =  0.001681519
Erro Quadratico Medio =  0.001679661
Erro Quadratico Medio =  0.001677811
Erro Quadratico Medio =  0.001675971
Erro Quadratico Medio =  0.00167414
Erro Quadratico Medio =  0.001672318
Erro Quadratico Medio =  0.001670505
Erro Quadratico Medio =  0.001668701
Erro Quadratico Medio =  0.001666906
Erro Quadratico Medio =  0.001665119
Erro Quadratico Medio =  0.001663341
Erro Quadratico Medio =  0.001661572
Erro Quadratico Medio =  0.001659811
Erro Quadratico Medio =  0.001658059
Erro Quadratico Medio =  0.001656316
Erro Quadratico Medio =  0.00165458
Erro Quadratico Medio =  0.001652854
Erro Quadratico Medio =  0.001651135
Erro Quadratico Medio =  0.001649425
Erro Quadratico Medio =  0.001647723
Erro Quadratico Medio =  0.001646029
Erro Quadratico Medio =  0.001644343
Erro Quadratico Medio =  0.001642665
Erro Quadratico Medio =  0.001640996
Erro Quadratico Medio =  0.001639334
Erro Quadratico Medio =  0.00163768
Erro Quadratico Medio =  0.001636034
Erro Quadratico Medio =  0.001634396
Erro Quadratico Medio =  0.001632765
Erro Quadratico Medio =  0.001631142
Erro Quadratico Medio =  0.001629527
Erro Quadratico Medio =  0.00162792
Erro Quadratico Medio =  0.00162632
Erro Quadratico Medio =  0.001624727
Erro Quadratico Medio =  0.001623142
Erro Quadratico Medio =  0.001621564
Erro Quadratico Medio =  0.001619994
Erro Quadratico Medio =  0.001618431
Erro Quadratico Medio =  0.001616875
Erro Quadratico Medio =  0.001615327
Erro Quadratico Medio =  0.001613785
Erro Quadratico Medio =  0.001612251
Erro Quadratico Medio =  0.001610724
Erro Quadratico Medio =  0.001609204
Erro Quadratico Medio =  0.001607691
Erro Quadratico Medio =  0.001606185
Erro Quadratico Medio =  0.001604685
Erro Quadratico Medio =  0.001603193
Erro Quadratico Medio =  0.001601707
Erro Quadratico Medio =  0.001600228
Erro Quadratico Medio =  0.001598756
Erro Quadratico Medio =  0.001597291
Erro Quadratico Medio =  0.001595832
Erro Quadratico Medio =  0.00159438
Erro Quadratico Medio =  0.001592934
Erro Quadratico Medio =  0.001591495
Erro Quadratico Medio =  0.001590063
Erro Quadratico Medio =  0.001588637
Erro Quadratico Medio =  0.001587217
Erro Quadratico Medio =  0.001585804
Erro Quadratico Medio =  0.001584397
Erro Quadratico Medio =  0.001582996
Erro Quadratico Medio =  0.001581601
Erro Quadratico Medio =  0.001580213
Erro Quadratico Medio =  0.001578831
Erro Quadratico Medio =  0.001577455
Erro Quadratico Medio =  0.001576085
Erro Quadratico Medio =  0.001574721
Erro Quadratico Medio =  0.001573363
Erro Quadratico Medio =  0.001572011
Erro Quadratico Medio =  0.001570666
Erro Quadratico Medio =  0.001569326
Erro Quadratico Medio =  0.001567992
Erro Quadratico Medio =  0.001566663
Erro Quadratico Medio =  0.001565341
Erro Quadratico Medio =  0.001564024
Erro Quadratico Medio =  0.001562713
Erro Quadratico Medio =  0.001561408
Erro Quadratico Medio =  0.001560108
Erro Quadratico Medio =  0.001558814
Erro Quadratico Medio =  0.001557526
Erro Quadratico Medio =  0.001556243
Erro Quadratico Medio =  0.001554966
Erro Quadratico Medio =  0.001553694
Erro Quadratico Medio =  0.001552428
Erro Quadratico Medio =  0.001551167
Erro Quadratico Medio =  0.001549911
Erro Quadratico Medio =  0.001548661
Erro Quadratico Medio =  0.001547416
Erro Quadratico Medio =  0.001546177
Erro Quadratico Medio =  0.001544942
Erro Quadratico Medio =  0.001543713
Erro Quadratico Medio =  0.001542489
Erro Quadratico Medio =  0.001541271
Erro Quadratico Medio =  0.001540057
Erro Quadratico Medio =  0.001538849
Erro Quadratico Medio =  0.001537646
Erro Quadratico Medio =  0.001536447
Erro Quadratico Medio =  0.001535254
Erro Quadratico Medio =  0.001534066
Erro Quadratico Medio =  0.001532882
Erro Quadratico Medio =  0.001531704
Erro Quadratico Medio =  0.001530531
Erro Quadratico Medio =  0.001529362
Erro Quadratico Medio =  0.001528198
Erro Quadratico Medio =  0.001527039
Erro Quadratico Medio =  0.001525885
Erro Quadratico Medio =  0.001524736
Erro Quadratico Medio =  0.001523591
Erro Quadratico Medio =  0.001522451
Erro Quadratico Medio =  0.001521316
Erro Quadratico Medio =  0.001520185
Erro Quadratico Medio =  0.001519059
Erro Quadratico Medio =  0.001517938
Erro Quadratico Medio =  0.001516821
Erro Quadratico Medio =  0.001515709
Erro Quadratico Medio =  0.001514601
Erro Quadratico Medio =  0.001513498
Erro Quadratico Medio =  0.001512399
Erro Quadratico Medio =  0.001511304
Erro Quadratico Medio =  0.001510214
Erro Quadratico Medio =  0.001509129
Erro Quadratico Medio =  0.001508048
Erro Quadratico Medio =  0.001506971
Erro Quadratico Medio =  0.001505898
Erro Quadratico Medio =  0.00150483
Erro Quadratico Medio =  0.001503766
Erro Quadratico Medio =  0.001502706
Erro Quadratico Medio =  0.00150165
Erro Quadratico Medio =  0.001500599
Erro Quadratico Medio =  0.001499551
Erro Quadratico Medio =  0.001498508
Erro Quadratico Medio =  0.001497469
Erro Quadratico Medio =  0.001496434
Erro Quadratico Medio =  0.001495404
Erro Quadratico Medio =  0.001494377
Erro Quadratico Medio =  0.001493354
Erro Quadratico Medio =  0.001492335
Erro Quadratico Medio =  0.00149132
Erro Quadratico Medio =  0.001490309
Erro Quadratico Medio =  0.001489302
Erro Quadratico Medio =  0.001488299
Erro Quadratico Medio =  0.0014873
Erro Quadratico Medio =  0.001486305
Erro Quadratico Medio =  0.001485314
Erro Quadratico Medio =  0.001484326
Erro Quadratico Medio =  0.001483342
Erro Quadratico Medio =  0.001482362
Erro Quadratico Medio =  0.001481386
Erro Quadratico Medio =  0.001480413
Erro Quadratico Medio =  0.001479444
Erro Quadratico Medio =  0.001478479
Erro Quadratico Medio =  0.001477518
Erro Quadratico Medio =  0.00147656
Erro Quadratico Medio =  0.001475606
Erro Quadratico Medio =  0.001474655
Erro Quadratico Medio =  0.001473708
Erro Quadratico Medio =  0.001472765
Erro Quadratico Medio =  0.001471825
Erro Quadratico Medio =  0.001470889
Erro Quadratico Medio =  0.001469956
Erro Quadratico Medio =  0.001469026
Erro Quadratico Medio =  0.0014681
Erro Quadratico Medio =  0.001467178

In [16]:
# Fazendo predicoes para cada exemplo de teste
predicoes <- vector()
for(i in 1:nrow(dados.teste)){

  pred <- mlp.propagacao(modelo$arq,dados.teste[i,1:2])$y.escondida.saida

  predicoes <- c(predicoes,pred)
}
print(predicoes)

  [1] 5.704904e-05 6.113333e-13 6.113329e-13 5.704904e-05 5.704904e-05
  [6] 6.113329e-13 6.113329e-13 7.406886e-13 5.704904e-05 9.944868e-09
 [11] 4.799102e-05 4.799102e-05 6.113329e-13 6.113329e-13 9.875349e-01
 [16] 4.799065e-05 6.113331e-13 3.128489e-06 6.113347e-13 6.113329e-13
 [21] 6.113417e-13 5.704798e-05 3.250007e-10 6.113389e-13 5.704884e-05
 [26] 6.185775e-13 6.137769e-13 6.113329e-13 6.113528e-13 9.997223e-01
 [31] 6.113329e-13 6.113329e-13 6.113329e-13 5.188676e-11 1.276570e-11
 [36] 9.997766e-01 6.113329e-13 4.799102e-05 6.113329e-13 4.799102e-05
 [41] 9.997768e-01 4.098795e-11 6.113329e-13 9.997768e-01 6.113331e-13
 [46] 6.113329e-13 5.704904e-05 3.870233e-12 6.113329e-13 6.477126e-13
 [51] 4.799169e-05 6.277353e-13 6.182763e-07 9.997768e-01 5.704606e-05
 [56] 6.471193e-13 6.113329e-13 6.113410e-13 5.704459e-05 4.797696e-05
 [61] 5.704936e-05 5.704904e-05 6.987097e-04 1.409935e-05 9.997312e-01
 [66] 4.799102e-05 7.799500e-05 5.704796e-05 1.975004e-05 5.702518e-05
 [71] 4.799099e-05 4.798901e-05 1.064682e-02 2.048386e-12 9.997036e-01
 [76] 6.113329e-13 4.799450e-05 6.115249e-13 1.141717e-12 4.797761e-05
 [81] 9.997768e-01 6.113329e-13 5.680341e-05 6.113347e-13 6.126624e-13
 [86] 6.113329e-13 6.114326e-13 4.799102e-05 6.126958e-13 1.324780e-03
 [91] 6.113330e-13 5.704939e-05 1.700557e-05 8.588544e-13 7.901027e-13
 [96] 9.873154e-01 4.788839e-05 4.799027e-05 6.113329e-13 5.703935e-05
[101] 6.113372e-13 6.113329e-13 6.113355e-13 6.113329e-13 6.113329e-13
[106] 5.704903e-05 4.799179e-05 6.226825e-13 9.997768e-01 6.114023e-13
[111] 4.799102e-05 5.704219e-05 9.988049e-01 4.470730e-05 9.997768e-01
[116] 6.113329e-13 6.342153e-03 6.329126e-12 1.319274e-05 5.704956e-05
[121] 5.704904e-05 5.704904e-05 4.799104e-05 1.005035e-11 4.255581e-05
[126] 4.799102e-05 6.113332e-13 5.706694e-05 4.799103e-05 9.997768e-01
[131] 6.113341e-13 6.870494e-13 4.799102e-05 4.303881e-05 4.705677e-05
[136] 2.514671e-07 6.994983e-13 6.121919e-13 5.704904e-05 4.010526e-09
[141] 9.997767e-01 2.410004e-12 5.704904e-05 6.113329e-13 6.139821e-13
[146] 3.415975e-04 2.264111e-04 9.997652e-01 9.997768e-01 6.116488e-13
[151] 6.113602e-13 4.776908e-05 4.800566e-05 1.079538e-04 9.997748e-01
[156] 5.704904e-05 9.997768e-01 6.113330e-13 6.690811e-12 1.076310e-10
[161] 4.805266e-05 4.845976e-05 5.704906e-05 5.309506e-05 1.528881e-12
[166] 6.152805e-13 9.997768e-01 5.793672e-05 9.997150e-01 5.704900e-05
[171] 6.113341e-13 4.799097e-05 9.997768e-01 4.799102e-05 9.997762e-01
[176] 3.711002e-06 6.113329e-13 4.584865e-05 6.587797e-06 6.492120e-13
[181] 6.857572e-05 6.113329e-13 5.704393e-05 9.997768e-01 9.997768e-01
[186] 9.997138e-01 5.704905e-05 9.997485e-01 6.113329e-13 4.799102e-05
[191] 4.799102e-05 5.704867e-05 6.113329e-13 4.799102e-05 6.115935e-13
[196] 3.921590e-04 6.113329e-13 3.367598e-05 5.173092e-11 4.847767e-05
[201] 5.704807e-05 9.997762e-01 6.884783e-07 5.834019e-08 4.799102e-05
[206] 5.704904e-05 7.073600e-13 4.799059e-05 1.540155e-03 1.174582e-04
[211] 8.357774e-01 4.898753e-05 4.799101e-05 6.113531e-13 2.566365e-12
[216] 4.799096e-05 9.930270e-01 6.115059e-13 6.113329e-13 6.113736e-13
[221] 5.704904e-05 9.997768e-01 4.822635e-05 9.997768e-01 1.055248e-12
[226] 1.911377e-05 6.113337e-13 4.792567e-05 9.941026e-01 5.789334e-05
[231] 9.997698e-01 5.704181e-05 4.294738e-02 4.799102e-05 4.799102e-05
[236] 4.795270e-05 5.704569e-05 4.799104e-05 4.799102e-05 6.116574e-13
[241] 9.997763e-01 5.704926e-05 5.704902e-05 3.676687e-05 6.113411e-13
[246] 4.799102e-05 5.704655e-05 7.131417e-05 5.707064e-05 4.799401e-05
[251] 6.113329e-13 4.799095e-05 3.580076e-05 5.832700e-05 6.113329e-13
[256] 5.011895e-05 6.113329e-13 6.113357e-13 6.113636e-13 5.704904e-05
[261] 5.704838e-05 1.307629e-07 1.485460e-09 1.322573e-08 5.704753e-05
[266] 4.799102e-05 5.704904e-05 9.997768e-01 5.704904e-05 5.704903e-05
[271] 8.906906e-13 4.799102e-05 5.814787e-05 6.654141e-04 5.704904e-05
[276] 4.799102e-05 4.800963e-05 5.704904e-05 5.704848e-05 5.704914e-05
[281] 5.711025e-05 6.698316e-13 1.456836e-05 9.997768e-01 6.113330e-13
[286] 3.872517e-05 9.997768e-01 4.957381e-09 6.113329e-13 5.704904e-05
[291] 4.799040e-05 6.113329e-13 6.113329e-13 6.113329e-13 4.471265e-05
[296] 6.113330e-13 1.420815e-04 4.800024e-05 6.113330e-13 5.704906e-05
[301] 2.198985e-12 5.704903e-05 5.704901e-05 4.799071e-05 1.641017e-05
[306] 4.799102e-05 4.799103e-05 6.113344e-13 4.799102e-05 5.701063e-05
[311] 5.704904e-05 6.200576e-13 5.704904e-05 6.113329e-13 6.113414e-13
[316] 6.130311e-13 9.997768e-01 3.279859e-06 8.602344e-13 5.705567e-05
[321] 9.997335e-01 6.113329e-13 5.222838e-05 5.300327e-05 5.704904e-05
[326] 9.997768e-01 9.221195e-06 4.785516e-05 4.798999e-05 6.113329e-13
[331] 3.022132e-05 9.997767e-01 9.997768e-01 4.792411e-05 4.799102e-05
[336] 6.113952e-13 6.529949e-13 5.704904e-05 4.799102e-05 9.997496e-01
[341] 1.787816e-06 4.799102e-05 7.477957e-07 4.798912e-05 2.497208e-03
[346] 5.676678e-05 4.839647e-05 5.496162e-05 5.704811e-05 7.280653e-13
[351] 4.159699e-05 2.954875e-04 4.799102e-05 6.113329e-13 4.798916e-05
[356] 9.997750e-01 6.113330e-13 2.230455e-12 6.114194e-13 4.913690e-05
[361] 7.002233e-05 9.962404e-01 1.352235e-06 5.704904e-05 6.114462e-13
[366] 1.485469e-09 4.799102e-05 5.704904e-05 3.513970e-10 6.113329e-13
[371] 4.799102e-05 6.113329e-13 6.168227e-13 9.997321e-01 4.775579e-05
[376] 6.113329e-13 5.704902e-05 4.504090e-04 6.113498e-13 5.704904e-05
[381] 4.799102e-05 6.113329e-13 4.797844e-05 5.667930e-05 7.311498e-08
[386] 5.705000e-05 6.123451e-13 6.113329e-13 4.799102e-05 1.029006e-12
[391] 9.997768e-01 6.113329e-13 4.792299e-05 6.113329e-13 4.591854e-05
[396] 6.113330e-13 4.676117e-05 6.113367e-13 3.399905e-06 6.137092e-13
[401] 5.704014e-05 5.704904e-05 5.704964e-05 5.704904e-05 5.704904e-05
[406] 6.099849e-06 4.799186e-05 8.991893e-01 5.704904e-05 4.799102e-05
[411] 5.704865e-05 7.143142e-11 6.113329e-13 6.113329e-13 4.799102e-05
[416] 1.488294e-04 4.799100e-05 5.704305e-05 6.431524e-13 6.114998e-13
[421] 6.113356e-13 4.756966e-05 4.348748e-01 6.113329e-13 9.997759e-01
[426] 5.811672e-05 5.711105e-05 2.193965e-03 6.113329e-13 4.799019e-05
[431] 6.113334e-13 2.085893e-06 8.139390e-13 6.113329e-13 9.996594e-01
[436] 9.997767e-01 6.113329e-13 5.704904e-05 4.658428e-05 1.274582e-05
[441] 9.997768e-01 1.972815e-12 3.857804e-05 9.997007e-01 5.704904e-05
[446] 6.113631e-13 9.997768e-01 5.704904e-05 9.997750e-01 9.997754e-01
[451] 5.704904e-05 5.704904e-05 5.704904e-05 2.626382e-05 4.371461e-05
[456] 4.798181e-05 4.799102e-05 4.799126e-05 6.183330e-13 6.119661e-13
[461] 9.997768e-01 7.130212e-01 6.118680e-13 9.985991e-01 9.997768e-01
[466] 6.113762e-13 9.997768e-01 3.089245e-03 1.619621e-07 5.704716e-05
[471] 6.113329e-13 6.113329e-13 9.991425e-01 6.114982e-13 5.211872e-05
[476] 6.113330e-13 4.799102e-05 6.113329e-13 6.113329e-13 6.113329e-13
[481] 9.997768e-01 7.178540e-13 4.799098e-05 4.799063e-05 4.799102e-05
[486] 6.113330e-13 1.983945e-10 6.157608e-13 1.076624e-12 6.113329e-13
[491] 5.704904e-05 4.129625e-12 4.799102e-05 4.799102e-05 3.536316e-10
[496] 5.715731e-05 6.113329e-13 1.603222e-05 5.704903e-05 6.113330e-13
[501] 5.743872e-05 5.248839e-05 5.598402e-05 9.995751e-01 5.704937e-05
[506] 6.113329e-13 6.140252e-13 5.704904e-05 9.997768e-01 5.699648e-05
[511] 3.399783e-10 4.798999e-05 1.452006e-12 6.114509e-13 9.997552e-01
[516] 4.798719e-05 9.507129e-11 5.704904e-05 6.113329e-13 5.704904e-05
[521] 6.113496e-13 6.113329e-13 5.704793e-05 5.211921e-05 9.995723e-01
[526] 5.704906e-05 6.113329e-13 5.704904e-05 9.997768e-01 8.032009e-12
[531] 9.997768e-01 6.116400e-13 4.302091e-05 3.594931e-11 6.113329e-13
[536] 6.113329e-13 4.797962e-05 4.798520e-05 2.318499e-11 6.113329e-13
[541] 9.997768e-01 6.423342e-13 6.113331e-13 4.799102e-05 5.708119e-05
[546] 4.799045e-05 5.704904e-05 1.326698e-12 3.193198e-05 5.704934e-05
[551] 6.113329e-13 6.134041e-13 6.115805e-13 4.799108e-05 6.113464e-13
[556] 5.704697e-05 6.131322e-13 5.704904e-05 9.997767e-01 8.005095e-13
[561] 1.018145e-11 1.103963e-12 2.836766e-12 9.997508e-01 9.997768e-01
[566] 5.787654e-05 7.719723e-01 7.193046e-13 6.113382e-13 5.704980e-05
[571] 6.113329e-13 4.784404e-05 5.704904e-05 6.113329e-13 4.709915e-05
[576] 6.113376e-13 5.704904e-05 4.728603e-05 5.627213e-05 6.113329e-13
[581] 6.987965e-13 6.113351e-13 5.704904e-05 9.995516e-01 6.113329e-13
[586] 6.262803e-13 6.789161e-13 5.614046e-04 5.439862e-05 9.997768e-01
[591] 5.106930e-06 6.113377e-13 4.799102e-05 4.799069e-05 7.512040e-13
[596] 6.113329e-13 4.799102e-05 9.989955e-01 6.113329e-13 6.472248e-13

In [17]:
# Criando uma matriz para comparação dos resultados
matriz.comparacao <- cbind(dados.teste[,3],predicoes)
colnames(matriz.comparacao) <- c('V','P')
print(matriz.comparacao)

       V            P
  [1,] 0 5.704904e-05
  [2,] 0 6.113333e-13
  [3,] 0 6.113329e-13
  [4,] 0 5.704904e-05
  [5,] 0 5.704904e-05
  [6,] 0 6.113329e-13
  [7,] 0 6.113329e-13
  [8,] 0 7.406886e-13
  [9,] 0 5.704904e-05
 [10,] 0 9.944868e-09
 [11,] 0 4.799102e-05
 [12,] 0 4.799102e-05
 [13,] 0 6.113329e-13
 [14,] 0 6.113329e-13
 [15,] 1 9.875349e-01
 [16,] 0 4.799065e-05
 [17,] 0 6.113331e-13
 [18,] 0 3.128489e-06
 [19,] 0 6.113347e-13
 [20,] 0 6.113329e-13
 [21,] 0 6.113417e-13
 [22,] 0 5.704798e-05
 [23,] 0 3.250007e-10
 [24,] 0 6.113389e-13
 [25,] 0 5.704884e-05
 [26,] 0 6.185775e-13
 [27,] 0 6.137769e-13
 [28,] 0 6.113329e-13
 [29,] 0 6.113528e-13
 [30,] 1 9.997223e-01
 [31,] 0 6.113329e-13
 [32,] 0 6.113329e-13
 [33,] 0 6.113329e-13
 [34,] 0 5.188676e-11
 [35,] 0 1.276570e-11
 [36,] 1 9.997766e-01
 [37,] 0 6.113329e-13
 [38,] 0 4.799102e-05
 [39,] 0 6.113329e-13
 [40,] 0 4.799102e-05
 [41,] 1 9.997768e-01
 [42,] 0 4.098795e-11
 [43,] 0 6.113329e-13
 [44,] 1 9.997768e-01
 [45,] 0 6.113331e-13
 [46,] 0 6.113329e-13
 [47,] 0 5.704904e-05
 [48,] 0 3.870233e-12
 [49,] 0 6.113329e-13
 [50,] 0 6.477126e-13
 [51,] 0 4.799169e-05
 [52,] 0 6.277353e-13
 [53,] 0 6.182763e-07
 [54,] 1 9.997768e-01
 [55,] 0 5.704606e-05
 [56,] 0 6.471193e-13
 [57,] 0 6.113329e-13
 [58,] 0 6.113410e-13
 [59,] 0 5.704459e-05
 [60,] 0 4.797696e-05
 [61,] 0 5.704936e-05
 [62,] 0 5.704904e-05
 [63,] 0 6.987097e-04
 [64,] 0 1.409935e-05
 [65,] 1 9.997312e-01
 [66,] 0 4.799102e-05
 [67,] 0 7.799500e-05
 [68,] 0 5.704796e-05
 [69,] 0 1.975004e-05
 [70,] 0 5.702518e-05
 [71,] 0 4.799099e-05
 [72,] 0 4.798901e-05
 [73,] 0 1.064682e-02
 [74,] 0 2.048386e-12
 [75,] 1 9.997036e-01
 [76,] 0 6.113329e-13
 [77,] 0 4.799450e-05
 [78,] 0 6.115249e-13
 [79,] 0 1.141717e-12
 [80,] 0 4.797761e-05
 [81,] 1 9.997768e-01
 [82,] 0 6.113329e-13
 [83,] 0 5.680341e-05
 [84,] 0 6.113347e-13
 [85,] 0 6.126624e-13
 [86,] 0 6.113329e-13
 [87,] 0 6.114326e-13
 [88,] 0 4.799102e-05
 [89,] 0 6.126958e-13
 [90,] 0 1.324780e-03
 [91,] 0 6.113330e-13
 [92,] 0 5.704939e-05
 [93,] 0 1.700557e-05
 [94,] 0 8.588544e-13
 [95,] 0 7.901027e-13
 [96,] 1 9.873154e-01
 [97,] 0 4.788839e-05
 [98,] 0 4.799027e-05
 [99,] 0 6.113329e-13
[100,] 0 5.703935e-05
[101,] 0 6.113372e-13
[102,] 0 6.113329e-13
[103,] 0 6.113355e-13
[104,] 0 6.113329e-13
[105,] 0 6.113329e-13
[106,] 0 5.704903e-05
[107,] 0 4.799179e-05
[108,] 0 6.226825e-13
[109,] 1 9.997768e-01
[110,] 0 6.114023e-13
[111,] 0 4.799102e-05
[112,] 0 5.704219e-05
[113,] 1 9.988049e-01
[114,] 0 4.470730e-05
[115,] 1 9.997768e-01
[116,] 0 6.113329e-13
[117,] 0 6.342153e-03
[118,] 0 6.329126e-12
[119,] 0 1.319274e-05
[120,] 0 5.704956e-05
[121,] 0 5.704904e-05
[122,] 0 5.704904e-05
[123,] 0 4.799104e-05
[124,] 0 1.005035e-11
[125,] 0 4.255581e-05
[126,] 0 4.799102e-05
[127,] 0 6.113332e-13
[128,] 0 5.706694e-05
[129,] 0 4.799103e-05
[130,] 1 9.997768e-01
[131,] 0 6.113341e-13
[132,] 0 6.870494e-13
[133,] 0 4.799102e-05
[134,] 0 4.303881e-05
[135,] 0 4.705677e-05
[136,] 0 2.514671e-07
[137,] 0 6.994983e-13
[138,] 0 6.121919e-13
[139,] 0 5.704904e-05
[140,] 0 4.010526e-09
[141,] 1 9.997767e-01
[142,] 0 2.410004e-12
[143,] 0 5.704904e-05
[144,] 0 6.113329e-13
[145,] 0 6.139821e-13
[146,] 0 3.415975e-04
[147,] 0 2.264111e-04
[148,] 1 9.997652e-01
[149,] 1 9.997768e-01
[150,] 0 6.116488e-13
[151,] 0 6.113602e-13
[152,] 0 4.776908e-05
[153,] 0 4.800566e-05
[154,] 0 1.079538e-04
[155,] 1 9.997748e-01
[156,] 0 5.704904e-05
[157,] 1 9.997768e-01
[158,] 0 6.113330e-13
[159,] 0 6.690811e-12
[160,] 0 1.076310e-10
[161,] 0 4.805266e-05
[162,] 0 4.845976e-05
[163,] 0 5.704906e-05
[164,] 0 5.309506e-05
[165,] 0 1.528881e-12
[166,] 0 6.152805e-13
[167,] 1 9.997768e-01
[168,] 0 5.793672e-05
[169,] 1 9.997150e-01
[170,] 0 5.704900e-05
[171,] 0 6.113341e-13
[172,] 0 4.799097e-05
[173,] 1 9.997768e-01
[174,] 0 4.799102e-05
[175,] 1 9.997762e-01
[176,] 0 3.711002e-06
[177,] 0 6.113329e-13
[178,] 0 4.584865e-05
[179,] 0 6.587797e-06
[180,] 0 6.492120e-13
[181,] 0 6.857572e-05
[182,] 0 6.113329e-13
[183,] 0 5.704393e-05
[184,] 1 9.997768e-01
[185,] 1 9.997768e-01
[186,] 1 9.997138e-01
[187,] 0 5.704905e-05
[188,] 1 9.997485e-01
[189,] 0 6.113329e-13
[190,] 0 4.799102e-05
[191,] 0 4.799102e-05
[192,] 0 5.704867e-05
[193,] 0 6.113329e-13
[194,] 0 4.799102e-05
[195,] 0 6.115935e-13
[196,] 0 3.921590e-04
[197,] 0 6.113329e-13
[198,] 0 3.367598e-05
[199,] 0 5.173092e-11
[200,] 0 4.847767e-05
[201,] 0 5.704807e-05
[202,] 1 9.997762e-01
[203,] 0 6.884783e-07
[204,] 0 5.834019e-08
[205,] 0 4.799102e-05
[206,] 0 5.704904e-05
[207,] 0 7.073600e-13
[208,] 0 4.799059e-05
[209,] 0 1.540155e-03
[210,] 0 1.174582e-04
[211,] 1 8.357774e-01
[212,] 0 4.898753e-05
[213,] 0 4.799101e-05
[214,] 0 6.113531e-13
[215,] 0 2.566365e-12
[216,] 0 4.799096e-05
[217,] 1 9.930270e-01
[218,] 0 6.115059e-13
[219,] 0 6.113329e-13
[220,] 0 6.113736e-13
[221,] 0 5.704904e-05
[222,] 1 9.997768e-01
[223,] 0 4.822635e-05
[224,] 1 9.997768e-01
[225,] 0 1.055248e-12
[226,] 0 1.911377e-05
[227,] 0 6.113337e-13
[228,] 0 4.792567e-05
[229,] 1 9.941026e-01
[230,] 0 5.789334e-05
[231,] 1 9.997698e-01
[232,] 0 5.704181e-05
[233,] 0 4.294738e-02
[234,] 0 4.799102e-05
[235,] 0 4.799102e-05
[236,] 0 4.795270e-05
[237,] 0 5.704569e-05
[238,] 0 4.799104e-05
[239,] 0 4.799102e-05
[240,] 0 6.116574e-13
[241,] 1 9.997763e-01
[242,] 0 5.704926e-05
[243,] 0 5.704902e-05
[244,] 0 3.676687e-05
[245,] 0 6.113411e-13
[246,] 0 4.799102e-05
[247,] 0 5.704655e-05
[248,] 0 7.131417e-05
[249,] 0 5.707064e-05
[250,] 0 4.799401e-05
[251,] 0 6.113329e-13
[252,] 0 4.799095e-05
[253,] 0 3.580076e-05
[254,] 0 5.832700e-05
[255,] 0 6.113329e-13
[256,] 0 5.011895e-05
[257,] 0 6.113329e-13
[258,] 0 6.113357e-13
[259,] 0 6.113636e-13
[260,] 0 5.704904e-05
[261,] 0 5.704838e-05
[262,] 0 1.307629e-07
[263,] 0 1.485460e-09
[264,] 0 1.322573e-08
[265,] 0 5.704753e-05
[266,] 0 4.799102e-05
[267,] 0 5.704904e-05
[268,] 1 9.997768e-01
[269,] 0 5.704904e-05
[270,] 0 5.704903e-05
[271,] 0 8.906906e-13
[272,] 0 4.799102e-05
[273,] 0 5.814787e-05
[274,] 0 6.654141e-04
[275,] 0 5.704904e-05
[276,] 0 4.799102e-05
[277,] 0 4.800963e-05
[278,] 0 5.704904e-05
[279,] 0 5.704848e-05
[280,] 0 5.704914e-05
[281,] 0 5.711025e-05
[282,] 0 6.698316e-13
[283,] 0 1.456836e-05
[284,] 1 9.997768e-01
[285,] 0 6.113330e-13
[286,] 0 3.872517e-05
[287,] 1 9.997768e-01
[288,] 0 4.957381e-09
[289,] 0 6.113329e-13
[290,] 0 5.704904e-05
[291,] 0 4.799040e-05
[292,] 0 6.113329e-13
[293,] 0 6.113329e-13
[294,] 0 6.113329e-13
[295,] 0 4.471265e-05
[296,] 0 6.113330e-13
[297,] 0 1.420815e-04
[298,] 0 4.800024e-05
[299,] 0 6.113330e-13
[300,] 0 5.704906e-05
[301,] 0 2.198985e-12
[302,] 0 5.704903e-05
[303,] 0 5.704901e-05
[304,] 0 4.799071e-05
[305,] 0 1.641017e-05
[306,] 0 4.799102e-05
[307,] 0 4.799103e-05
[308,] 0 6.113344e-13
[309,] 0 4.799102e-05
[310,] 0 5.701063e-05
[311,] 0 5.704904e-05
[312,] 0 6.200576e-13
[313,] 0 5.704904e-05
[314,] 0 6.113329e-13
[315,] 0 6.113414e-13
[316,] 0 6.130311e-13
[317,] 1 9.997768e-01
[318,] 0 3.279859e-06
[319,] 0 8.602344e-13
[320,] 0 5.705567e-05
[321,] 1 9.997335e-01
[322,] 0 6.113329e-13
[323,] 0 5.222838e-05
[324,] 0 5.300327e-05
[325,] 0 5.704904e-05
[326,] 1 9.997768e-01
[327,] 0 9.221195e-06
[328,] 0 4.785516e-05
[329,] 0 4.798999e-05
[330,] 0 6.113329e-13
[331,] 0 3.022132e-05
[332,] 1 9.997767e-01
[333,] 1 9.997768e-01
[334,] 0 4.792411e-05
[335,] 0 4.799102e-05
[336,] 0 6.113952e-13
[337,] 0 6.529949e-13
[338,] 0 5.704904e-05
[339,] 0 4.799102e-05
[340,] 1 9.997496e-01
[341,] 0 1.787816e-06
[342,] 0 4.799102e-05
[343,] 0 7.477957e-07
[344,] 0 4.798912e-05
[345,] 0 2.497208e-03
[346,] 0 5.676678e-05
[347,] 0 4.839647e-05
[348,] 0 5.496162e-05
[349,] 0 5.704811e-05
[350,] 0 7.280653e-13
[351,] 0 4.159699e-05
[352,] 0 2.954875e-04
[353,] 0 4.799102e-05
[354,] 0 6.113329e-13
[355,] 0 4.798916e-05
[356,] 1 9.997750e-01
[357,] 0 6.113330e-13
[358,] 0 2.230455e-12
[359,] 0 6.114194e-13
[360,] 0 4.913690e-05
[361,] 0 7.002233e-05
[362,] 1 9.962404e-01
[363,] 0 1.352235e-06
[364,] 0 5.704904e-05
[365,] 0 6.114462e-13
[366,] 0 1.485469e-09
[367,] 0 4.799102e-05
[368,] 0 5.704904e-05
[369,] 0 3.513970e-10
[370,] 0 6.113329e-13
[371,] 0 4.799102e-05
[372,] 0 6.113329e-13
[373,] 0 6.168227e-13
[374,] 1 9.997321e-01
[375,] 0 4.775579e-05
[376,] 0 6.113329e-13
[377,] 0 5.704902e-05
[378,] 0 4.504090e-04
[379,] 0 6.113498e-13
[380,] 0 5.704904e-05
[381,] 0 4.799102e-05
[382,] 0 6.113329e-13
[383,] 0 4.797844e-05
[384,] 0 5.667930e-05
[385,] 0 7.311498e-08
[386,] 0 5.705000e-05
[387,] 0 6.123451e-13
[388,] 0 6.113329e-13
[389,] 0 4.799102e-05
[390,] 0 1.029006e-12
[391,] 1 9.997768e-01
[392,] 0 6.113329e-13
[393,] 0 4.792299e-05
[394,] 0 6.113329e-13
[395,] 0 4.591854e-05
[396,] 0 6.113330e-13
[397,] 0 4.676117e-05
[398,] 0 6.113367e-13
[399,] 0 3.399905e-06
[400,] 0 6.137092e-13
[401,] 0 5.704014e-05
[402,] 0 5.704904e-05
[403,] 0 5.704964e-05
[404,] 0 5.704904e-05
[405,] 0 5.704904e-05
[406,] 0 6.099849e-06
[407,] 0 4.799186e-05
[408,] 1 8.991893e-01
[409,] 0 5.704904e-05
[410,] 0 4.799102e-05
[411,] 0 5.704865e-05
[412,] 0 7.143142e-11
[413,] 0 6.113329e-13
[414,] 0 6.113329e-13
[415,] 0 4.799102e-05
[416,] 0 1.488294e-04
[417,] 0 4.799100e-05
[418,] 0 5.704305e-05
[419,] 0 6.431524e-13
[420,] 0 6.114998e-13
[421,] 0 6.113356e-13
[422,] 0 4.756966e-05
[423,] 0 4.348748e-01
[424,] 0 6.113329e-13
[425,] 1 9.997759e-01
[426,] 0 5.811672e-05
[427,] 0 5.711105e-05
[428,] 0 2.193965e-03
[429,] 0 6.113329e-13
[430,] 0 4.799019e-05
[431,] 0 6.113334e-13
[432,] 0 2.085893e-06
[433,] 0 8.139390e-13
[434,] 0 6.113329e-13
[435,] 1 9.996594e-01
[436,] 1 9.997767e-01
[437,] 0 6.113329e-13
[438,] 0 5.704904e-05
[439,] 0 4.658428e-05
[440,] 0 1.274582e-05
[441,] 1 9.997768e-01
[442,] 0 1.972815e-12
[443,] 0 3.857804e-05
[444,] 1 9.997007e-01
[445,] 0 5.704904e-05
[446,] 0 6.113631e-13
[447,] 1 9.997768e-01
[448,] 0 5.704904e-05
[449,] 1 9.997750e-01
[450,] 1 9.997754e-01
[451,] 0 5.704904e-05
[452,] 0 5.704904e-05
[453,] 0 5.704904e-05
[454,] 0 2.626382e-05
[455,] 0 4.371461e-05
[456,] 0 4.798181e-05
[457,] 0 4.799102e-05
[458,] 0 4.799126e-05
[459,] 0 6.183330e-13
[460,] 0 6.119661e-13
[461,] 1 9.997768e-01
[462,] 1 7.130212e-01
[463,] 0 6.118680e-13
[464,] 1 9.985991e-01
[465,] 1 9.997768e-01
[466,] 0 6.113762e-13
[467,] 1 9.997768e-01
[468,] 0 3.089245e-03
[469,] 0 1.619621e-07
[470,] 0 5.704716e-05
[471,] 0 6.113329e-13
[472,] 0 6.113329e-13
[473,] 1 9.991425e-01
[474,] 0 6.114982e-13
[475,] 0 5.211872e-05
[476,] 0 6.113330e-13
[477,] 0 4.799102e-05
[478,] 0 6.113329e-13
[479,] 0 6.113329e-13
[480,] 0 6.113329e-13
[481,] 1 9.997768e-01
[482,] 0 7.178540e-13
[483,] 0 4.799098e-05
[484,] 0 4.799063e-05
[485,] 0 4.799102e-05
[486,] 0 6.113330e-13
[487,] 0 1.983945e-10
[488,] 0 6.157608e-13
[489,] 0 1.076624e-12
[490,] 0 6.113329e-13
[491,] 0 5.704904e-05
[492,] 0 4.129625e-12
[493,] 0 4.799102e-05
[494,] 0 4.799102e-05
[495,] 0 3.536316e-10
[496,] 0 5.715731e-05
[497,] 0 6.113329e-13
[498,] 0 1.603222e-05
[499,] 0 5.704903e-05
[500,] 0 6.113330e-13
[501,] 0 5.743872e-05
[502,] 0 5.248839e-05
[503,] 0 5.598402e-05
[504,] 1 9.995751e-01
[505,] 0 5.704937e-05
[506,] 0 6.113329e-13
[507,] 0 6.140252e-13
[508,] 0 5.704904e-05
[509,] 1 9.997768e-01
[510,] 0 5.699648e-05
[511,] 0 3.399783e-10
[512,] 0 4.798999e-05
[513,] 0 1.452006e-12
[514,] 0 6.114509e-13
[515,] 1 9.997552e-01
[516,] 0 4.798719e-05
[517,] 0 9.507129e-11
[518,] 0 5.704904e-05
[519,] 0 6.113329e-13
[520,] 0 5.704904e-05
[521,] 0 6.113496e-13
[522,] 0 6.113329e-13
[523,] 0 5.704793e-05
[524,] 0 5.211921e-05
[525,] 1 9.995723e-01
[526,] 0 5.704906e-05
[527,] 0 6.113329e-13
[528,] 0 5.704904e-05
[529,] 1 9.997768e-01
[530,] 0 8.032009e-12
[531,] 1 9.997768e-01
[532,] 0 6.116400e-13
[533,] 0 4.302091e-05
[534,] 0 3.594931e-11
[535,] 0 6.113329e-13
[536,] 0 6.113329e-13
[537,] 0 4.797962e-05
[538,] 0 4.798520e-05
[539,] 0 2.318499e-11
[540,] 0 6.113329e-13
[541,] 1 9.997768e-01
[542,] 0 6.423342e-13
[543,] 0 6.113331e-13
[544,] 0 4.799102e-05
[545,] 0 5.708119e-05
[546,] 0 4.799045e-05
[547,] 0 5.704904e-05
[548,] 0 1.326698e-12
[549,] 0 3.193198e-05
[550,] 0 5.704934e-05
[551,] 0 6.113329e-13
[552,] 0 6.134041e-13
[553,] 0 6.115805e-13
[554,] 0 4.799108e-05
[555,] 0 6.113464e-13
[556,] 0 5.704697e-05
[557,] 0 6.131322e-13
[558,] 0 5.704904e-05
[559,] 1 9.997767e-01
[560,] 0 8.005095e-13
[561,] 0 1.018145e-11
[562,] 0 1.103963e-12
[563,] 0 2.836766e-12
[564,] 1 9.997508e-01
[565,] 1 9.997768e-01
[566,] 0 5.787654e-05
[567,] 1 7.719723e-01
[568,] 0 7.193046e-13
[569,] 0 6.113382e-13
[570,] 0 5.704980e-05
[571,] 0 6.113329e-13
[572,] 0 4.784404e-05
[573,] 0 5.704904e-05
[574,] 0 6.113329e-13
[575,] 0 4.709915e-05
[576,] 0 6.113376e-13
[577,] 0 5.704904e-05
[578,] 0 4.728603e-05
[579,] 0 5.627213e-05
[580,] 0 6.113329e-13
[581,] 0 6.987965e-13
[582,] 0 6.113351e-13
[583,] 0 5.704904e-05
[584,] 1 9.995516e-01
[585,] 0 6.113329e-13
[586,] 0 6.262803e-13
[587,] 0 6.789161e-13
[588,] 0 5.614046e-04
[589,] 0 5.439862e-05
[590,] 1 9.997768e-01
[591,] 0 5.106930e-06
[592,] 0 6.113377e-13
[593,] 0 4.799102e-05
[594,] 0 4.799069e-05
[595,] 0 7.512040e-13
[596,] 0 6.113329e-13
[597,] 0 4.799102e-05
[598,] 1 9.989955e-01
[599,] 0 6.113329e-13
[600,] 0 6.472248e-13

In [18]:
# Matriz de confusão com o arredondamento das predições
mc <- table(matriz.comparacao[,1],round(matriz.comparacao[,2]))
print(mc)

acc <- sum(diag(mc))/sum(mc)
print(acc)
sum(mc)
sum(diag(mc))

      0   1
  0 522   0
  1   0  78
[1] 1

[1] 600

[1] 600